// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cnet_oykryo.Infrastructure.Data;

#nullable disable

namespace cnet_oykryo.web.api.Migrations
{
    [DbContext(typeof(EPSDBContext))]
    partial class EPSDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("cnet_oykryo.domain.Entities.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "123456",
                            Balance = 2000m,
                            CustomerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "65231",
                            Balance = 2500m,
                            CustomerId = 2
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "8523",
                            Balance = 2900m,
                            CustomerId = 3
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = "69874",
                            Balance = 2500m,
                            CustomerId = 4
                        });
                });

            modelBuilder.Entity("cnet_oykryo.domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Arisha Barron"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Branden Gibson"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rhonda Church"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Georgina Hazel"
                        });
                });

            modelBuilder.Entity("cnet_oykryo.domain.Entities.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DestinationAccountId")
                        .HasColumnType("int");

                    b.Property<int>("SourceAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("SourceAccountId");

                    b.ToTable("Transfers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10m,
                            DestinationAccountId = 1,
                            SourceAccountId = 4,
                            TransferDate = new DateTime(2024, 1, 30, 13, 24, 8, 552, DateTimeKind.Local).AddTicks(8885)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 50m,
                            DestinationAccountId = 2,
                            SourceAccountId = 3,
                            TransferDate = new DateTime(2024, 1, 30, 13, 24, 8, 552, DateTimeKind.Local).AddTicks(8898)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 100m,
                            DestinationAccountId = 3,
                            SourceAccountId = 2,
                            TransferDate = new DateTime(2024, 1, 30, 13, 24, 8, 552, DateTimeKind.Local).AddTicks(8925)
                        },
                        new
                        {
                            Id = 4,
                            Amount = 75m,
                            DestinationAccountId = 4,
                            SourceAccountId = 1,
                            TransferDate = new DateTime(2024, 1, 30, 13, 24, 8, 552, DateTimeKind.Local).AddTicks(8926)
                        });
                });

            modelBuilder.Entity("cnet_oykryo.domain.Entities.BankAccount", b =>
                {
                    b.HasOne("cnet_oykryo.domain.Entities.Customer", "Customer")
                        .WithMany("BankAccounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("cnet_oykryo.domain.Entities.Transfer", b =>
                {
                    b.HasOne("cnet_oykryo.domain.Entities.BankAccount", "DestinationAccount")
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("cnet_oykryo.domain.Entities.BankAccount", "SourceAccount")
                        .WithMany("Transfers")
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DestinationAccount");

                    b.Navigation("SourceAccount");
                });

            modelBuilder.Entity("cnet_oykryo.domain.Entities.BankAccount", b =>
                {
                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("cnet_oykryo.domain.Entities.Customer", b =>
                {
                    b.Navigation("BankAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
